### ISSUE TITLE
no way to split essentia (in units)

### ISSUE THREAD

**Issue by jaquelinelorn** [CumulusMC/Art-of-Alchemy#19]
I can't make a philosofer's stone cause I can't get specifically 300 of each unit.
is this just me missing something??

**Comment by Sturmlilie** [comment]
You're not missing anything, there is no way that I'm aware of to split essentia into smaller amounts. The most you can do is split based on type, via the centrifuges.
Note that you don't have to hit exactly 300, you can go over a little (based on how much capacity you have left).

**Comment by eric-robertson** [comment]
I know this is closed and works as intended, but this is very limiting and makes working with the mod very difficult. Can I request some sort of support for splitting essentia?

For example, the vessel has modes, can there be a few modes added for limited essentia pulling? ( IE a `small` mode where it takes up to 50, and a `medium` mode where it takes up to 300)

**Comment by Sturmlilie** [comment]
@eric-robertson I understand your issue, though note that dealing with numbers and calculating correct ratios of essentia is one of the specific challenges of this mod. There are probably some tricks you can do, like synthesizing an object you don't need in order to use up some specific essentia.
Until there is REI support, you can check the csv document for an overview of all materials: https://github.com/CumulusMC/Art-of-Alchemy/blob/1.16/src/main/resources/data/artofalchemy/recipes/sheet.csv
